services:
  ghost:
    image: ghost:6-alpine
    restart: always
    environment:
      # These refer to the Environment Variables tab
      database__client: mysql
      database__connection__host: ${database__connection__host}
      database__connection__user: ${database__connection__user}
      database__connection__password: ${database__connection__password}
      database__connection__database: ${database__connection__database}
      url: ${url}
      # Required for Node.js to talk to MySQL 8 correctly
      database__connection__charset: utf8mb4
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
